// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package projects

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"
)

// Bala writer constants — internal to writeBala.
const (
	// Version 4 mirrors the build-project layout: the default
	// module's .bal files live at the bala root and only sub-modules
	// nest under modules/.
	balaSchemaVersion        = "4"
	balaImplementationVendor = "WSO2"
	balaLanguageSpecVersion  = "2024R1"
	dependenciesTomlVersion  = "2"
)

// writeBala builds the bala zip at outputDir/<org>-<name>-any-<ver>.bala.
func writeBala(pkg *Package, resolution *PackageResolution, outputDir string) (string, error) {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return "", fmt.Errorf("writeBala: create output directory: %w", err)
	}

	desc := pkg.Manifest().PackageDescriptor()
	balaName := fmt.Sprintf("%s-%s-%s-%s%s",
		desc.Org().String(), desc.Name().String(),
		BalaPlatformAny, desc.Version().String(), BalaFileExtension)
	balaPath := filepath.Join(outputDir, balaName)

	out, err := os.Create(balaPath)
	if err != nil {
		return "", fmt.Errorf("writeBala: create archive: %w", err)
	}

	zw := zip.NewWriter(out)
	if err := populateBalaArchive(zw, pkg, resolution); err != nil {
		_ = zw.Close()
		_ = out.Close()
		_ = os.Remove(balaPath)
		return "", err
	}
	if err := zw.Close(); err != nil {
		_ = out.Close()
		_ = os.Remove(balaPath)
		return "", fmt.Errorf("writeBala: finalize archive: %w", err)
	}
	if err := out.Close(); err != nil {
		_ = os.Remove(balaPath)
		return "", fmt.Errorf("writeBala: close archive: %w", err)
	}
	return balaPath, nil
}

// populateBalaArchive writes every entry of the bala layout into zw. The
// caller is responsible for closing zw. written tracks every zip path
// written so far across all stages, so a later stage (in practice, only
// addIncludes) can silently skip a path some earlier stage already wrote —
// matching Java's BalaWriter, which relies on ZipOutputStream throwing on
// any duplicate entry name and swallows that specific exception only
// around its own addIncludes call.
func populateBalaArchive(zw *zip.Writer, pkg *Package, resolution *PackageResolution) error {
	written := make(map[string]bool)
	if err := writeBalaToml(zw, pkg, written); err != nil {
		return err
	}
	if err := copyBallerinaToml(zw, pkg, written); err != nil {
		return err
	}
	if err := writeDependenciesToml(zw, pkg, resolution, written); err != nil {
		return err
	}
	if err := writeModuleSources(zw, pkg, written); err != nil {
		return err
	}
	if err := addIncludes(zw, pkg, written); err != nil {
		return err
	}
	return nil
}

func writeBalaToml(zw *zip.Writer, pkg *Package, written map[string]bool) error {
	manifest := pkg.Manifest()

	var b strings.Builder
	fmt.Fprintf(&b, "[bala]\n")
	fmt.Fprintf(&b, "schema_version = %q\n\n", balaSchemaVersion)

	fmt.Fprintf(&b, "[build]\n")
	fmt.Fprintf(&b, "ballerina_version      = %q\n", manifest.BallerinaVersion())
	fmt.Fprintf(&b, "implementation_vendor  = %q\n", balaImplementationVendor)
	fmt.Fprintf(&b, "language_spec_version  = %q\n", balaLanguageSpecVersion)
	fmt.Fprintf(&b, "platform               = %q\n", BalaPlatformAny)

	return writeZipEntry(zw, BalaTomlFile, []byte(b.String()), written)
}

func copyBallerinaToml(zw *zip.Writer, pkg *Package, written map[string]bool) error {
	bt := pkg.BallerinaToml()
	if bt == nil {
		return fmt.Errorf("writeBala: package has no Ballerina.toml")
	}

	return writeZipEntry(zw, BallerinaTomlFile, []byte(bt.Content()), written)
}

// writeDependenciesToml emits Dependencies.toml into zw: a lock file with one
// [[package]] entry per node in the resolved dependency graph, in topological
// order. Each entry lists its direct dependencies as an inline-table array.
func writeDependenciesToml(zw *zip.Writer, pkg *Package, resolution *PackageResolution, written map[string]bool) error {
	var b strings.Builder
	b.WriteString("# AUTO-GENERATED FILE. DO NOT MODIFY.\n")
	b.WriteString("#\n")
	b.WriteString("# This file is auto-generated by Ballerina for managing dependency versions.\n")
	b.WriteString("# It should not be modified by hand.\n\n")

	fmt.Fprintf(&b, "[ballerina]\n")
	fmt.Fprintf(&b, "dependencies-toml-version = %q\n", dependenciesTomlVersion)

	graph := resolution.DependencyGraph()
	for _, node := range graph.ToTopologicallySortedList() {
		directs := graph.DirectDependencies(node)
		slices.SortFunc(directs, packageDescriptorCmp)
		writeDependenciesPackageEntry(&b,
			node.Org().String(), node.Name().String(), node.Version().String(),
			directs)
	}
	return writeZipEntry(zw, DependenciesTomlFile, []byte(b.String()), written)
}

// writeDependenciesPackageEntry emits one [[package]] block. When directs is
// non-empty it appends a `dependencies = [...]` inline-table array. A nil/empty
// directs slice omits the line entirely (no `dependencies = []`).
func writeDependenciesPackageEntry(b *strings.Builder, org, name, version string, directs []PackageDescriptor) {
	fmt.Fprintf(b, "\n[[package]]\n")
	fmt.Fprintf(b, "org     = %q\n", org)
	fmt.Fprintf(b, "name    = %q\n", name)
	fmt.Fprintf(b, "version = %q\n", version)
	if len(directs) == 0 {
		return
	}
	b.WriteString("dependencies = [\n")
	for i, d := range directs {
		fmt.Fprintf(b, "    {org = %q, name = %q}", d.Org().String(), d.Name().String())
		if i < len(directs)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("]\n")
}

// writeModuleSources adds each module's .bal files: default-module sources
// at the bala root, sub-module sources under modules/<sub>/. Tests are
// excluded — downstream packages don't consume them.
func writeModuleSources(zw *zip.Writer, pkg *Package, written map[string]bool) error {
	for _, mod := range pkg.Modules() {
		var dir string
		if !mod.IsDefaultModule() {
			dir = ModulesDir + "/" + mod.ModuleName().ModuleNamePart()
		}
		for _, docID := range mod.DocumentIDs() {
			doc := mod.Document(docID)
			if doc == nil {
				continue
			}
			// bala stores files by base name; Document.Name() may be path-joined.
			fileName := path.Base(doc.Name())
			zipPath := fileName
			if dir != "" {
				zipPath = dir + "/" + fileName
			}
			content := []byte(doc.TextDocument().String())
			if err := writeZipEntry(zw, zipPath, content, written); err != nil {
				return err
			}
		}
	}
	return nil
}

// addIncludes copies files matching the package manifest's `include` glob
// patterns into zw, at the same path they occupy relative to the project
// root. resolveIncludePaths already expands a directory match into its
// individual files, so every path here is a file (never a directory) —
// which is what lets a later "!" pattern negate one specific file inside an
// otherwise-included directory. Reads go through the project's own fs.FS,
// same as every other project source read — pkg.Project().SourceRoot() is a
// path within that fs.FS (conventionally "."), not necessarily an
// OS-walkable directory. written already holds every path the earlier
// archive stages (toml files, module sources) wrote, so an include pattern
// colliding with one of those — or with another include match — is
// silently skipped rather than producing a bala with a duplicate zip entry.
// Java source: io.ballerina.projects.BalaWriter#addIncludes, which achieves
// the same outcome by catching ZipOutputStream's duplicate-entry exception.
func addIncludes(zw *zip.Writer, pkg *Package, written map[string]bool) error {
	patterns := pkg.Manifest().Include()
	if len(patterns) == 0 {
		return nil
	}

	fsys := pkg.Project().Environment().fs()
	root := pkg.Project().SourceRoot()
	relPaths, err := resolveIncludePaths(fsys, patterns, root)
	if err != nil {
		return err
	}

	for _, relPath := range relPaths {
		if err := addIncludeFile(zw, fsys, joinRoot(root, relPath), relPath, written); err != nil {
			return err
		}
	}
	return nil
}

// addIncludeFile writes a single include file into zw at relPath, skipping
// paths already written — an include pattern may match the same path
// twice, or match a path some earlier archive stage already wrote.
func addIncludeFile(zw *zip.Writer, fsys fs.FS, fsPath, relPath string, written map[string]bool) error {
	if written[relPath] {
		return nil
	}
	content, err := fs.ReadFile(fsys, fsPath)
	if err != nil {
		return fmt.Errorf("writeBala: read include file %s: %w", relPath, err)
	}
	return writeZipEntry(zw, relPath, content, written)
}

// writeZipEntry writes content into zw at zipPath and records zipPath in
// written. Callers other than addIncludeFile don't consult written
// themselves — see populateBalaArchive's doc comment for why only
// addIncludes needs to check it before writing.
func writeZipEntry(zw *zip.Writer, zipPath string, content []byte, written map[string]bool) error {
	w, err := zw.Create(zipPath)
	if err != nil {
		return fmt.Errorf("writeBala: create entry %s: %w", zipPath, err)
	}
	if _, err := io.Copy(w, bytes.NewReader(content)); err != nil {
		return fmt.Errorf("writeBala: write entry %s: %w", zipPath, err)
	}
	written[zipPath] = true
	return nil
}
