// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package main

import (
	"bytes"
	"fmt"
	goast "go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"

	"github.com/ballerina-nutcracker/ballerina/common/tomlparser"
)

const (
	registryDirectory       = "compilerpluginregistry"
	stdlibDirectory         = "lib/stdlibs"
	ballerinaManifestFile   = "Ballerina.toml"
	compilerPluginManifest  = "CompilerPlugin.toml"
	compilerPluginDirectory = "compilerplugin"
	afterSemantics          = "after-semantics"
)

type pluginDeclaration struct {
	Org        string
	Package    string
	Function   string
	Stage      string
	importPath string
}

func generate(root string) ([]byte, error) {
	entries, err := loadPlugins(root)
	if err != nil {
		return nil, err
	}
	var source bytes.Buffer
	source.WriteString("// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).\n")
	source.WriteString("//\n// WSO2 LLC. licenses this file to you under the Apache License,\n")
	source.WriteString("// Version 2.0 (the \"License\"); you may not use this file except\n")
	source.WriteString("// in compliance with the License.\n// You may obtain a copy of the License at\n//\n")
	source.WriteString("// http://www.apache.org/licenses/LICENSE-2.0\n//\n")
	source.WriteString("// Unless required by applicable law or agreed to in writing,\n")
	source.WriteString("// software distributed under the License is distributed on an\n")
	source.WriteString("// \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY\n")
	source.WriteString("// KIND, either express or implied.  See the License for the\n")
	source.WriteString("// specific language governing permissions and limitations\n// under the License.\n\n")
	source.WriteString("// Code generated by compiler-tools/plugin-gen. DO NOT EDIT.\n\n")
	source.WriteString("package compilerpluginregistry\n\n")
	source.WriteString("import (\n\t\"github.com/ballerina-nutcracker/ballerina/compilerplugin\"\n")
	importedProviders := make(map[string]struct{})
	for _, entry := range entries {
		provider := providerKey(entry.Org, entry.Package)
		if _, imported := importedProviders[provider]; imported {
			continue
		}
		importedProviders[provider] = struct{}{}
		fmt.Fprintf(&source, "\t%s %q\n", pluginImportAlias(entry.Org, entry.Package), entry.importPath)
	}
	source.WriteString(")\n\n")
	source.WriteString("// RegisterPlugins registers every statically linked compiler plugin.\n")
	source.WriteString("func RegisterPlugins(register Register) {\n")
	for _, entry := range entries {
		fmt.Fprintf(&source, "\tregister(%q, %q, %q, compilerplugin.CompilerPlugin{\n", entry.Org, entry.Package, entry.Function)
		source.WriteString("\t\tAfter: compilerplugin.AfterSemantics,\n")
		fmt.Fprintf(&source, "\t\tPackageTransformer: %s.%s,\n", pluginImportAlias(entry.Org, entry.Package), entry.Function)
		source.WriteString("\t})\n")
	}
	source.WriteString("}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated registry: %w", err)
	}
	return formatted, nil
}

func loadPlugins(root string) ([]pluginDeclaration, error) {
	manifestPaths, err := findCompilerPluginManifests(root)
	if err != nil {
		return nil, err
	}
	if len(manifestPaths) == 0 {
		return nil, fmt.Errorf("no %s files found under %s", compilerPluginManifest, filepath.Join(root, stdlibDirectory))
	}

	var plugins []pluginDeclaration
	seen := make(map[string]struct{})
	for _, manifestPath := range manifestPaths {
		manifestDirectory := filepath.Dir(manifestPath)
		org, pkg, err := readPackageIdentity(filepath.Join(manifestDirectory, ballerinaManifestFile))
		if err != nil {
			return nil, err
		}
		content, err := os.ReadFile(manifestPath)
		if err != nil {
			return nil, err
		}
		doc, err := tomlparser.ReadString(string(content))
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", manifestPath, err)
		}
		tables, ok := doc.GetTables("plugin")
		if !ok || len(tables) == 0 {
			return nil, fmt.Errorf("%s must contain at least one [[plugin]] entry", manifestPath)
		}
		implementationDirectory := filepath.Join(manifestDirectory, compilerPluginDirectory)
		moduleRoot, modulePath, err := nearestModule(implementationDirectory)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", manifestPath, err)
		}
		relative, err := filepath.Rel(moduleRoot, implementationDirectory)
		if err != nil {
			return nil, err
		}
		importPath := strings.TrimSuffix(modulePath, "/")
		if relative != "." {
			importPath += "/" + filepath.ToSlash(relative)
		}
		for i, table := range tables {
			stage, ok := table.GetString("stage")
			if !ok {
				return nil, fmt.Errorf("%s: plugin entry %d must define a string stage", manifestPath, i+1)
			}
			if stage != afterSemantics {
				return nil, fmt.Errorf("%s: plugin entry %d has unsupported stage %q", manifestPath, i+1, stage)
			}
			function, ok := table.GetString("function")
			if !ok || !token.IsIdentifier(function) || !goast.IsExported(function) {
				return nil, fmt.Errorf("%s: plugin entry %d has invalid exported Go function %q", manifestPath, i+1, function)
			}
			key := org + "\x00" + pkg + "\x00" + stage + "\x00" + function
			if _, exists := seen[key]; exists {
				return nil, fmt.Errorf("%s: duplicate compiler plugin registration for %s/%s:%s", manifestPath, org, pkg, function)
			}
			seen[key] = struct{}{}
			if err := requireFunction(implementationDirectory, function); err != nil {
				return nil, fmt.Errorf("%s: %w", manifestPath, err)
			}
			plugins = append(plugins, pluginDeclaration{
				Org: org, Package: pkg, Function: function, Stage: stage, importPath: importPath,
			})
		}
	}
	slices.SortStableFunc(plugins, func(a, b pluginDeclaration) int {
		if compared := strings.Compare(a.Org, b.Org); compared != 0 {
			return compared
		}
		return strings.Compare(a.Package, b.Package)
	})
	return plugins, nil
}

func findCompilerPluginManifests(root string) ([]string, error) {
	stdlibRoot := filepath.Join(root, stdlibDirectory)
	var manifests []string
	err := filepath.WalkDir(stdlibRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() && entry.Name() == compilerPluginManifest {
			manifests = append(manifests, path)
		}
		return nil
	})
	return manifests, err
}

func readPackageIdentity(path string) (string, string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", "", err
	}
	doc, err := tomlparser.ReadString(string(content))
	if err != nil {
		return "", "", fmt.Errorf("parse %s: %w", path, err)
	}
	org, hasOrg := doc.GetString("package.org")
	pkg, hasPackage := doc.GetString("package.name")
	if !hasOrg || org == "" || !hasPackage || pkg == "" {
		return "", "", fmt.Errorf("%s must define package.org and package.name", path)
	}
	return org, pkg, nil
}

func providerKey(org, pkg string) string {
	return org + "\x00" + pkg
}

func pluginImportAlias(org, pkg string) string {
	var alias strings.Builder
	for index, char := range org + "_" + pkg {
		if char == '_' || unicode.IsLetter(char) || index > 0 && unicode.IsDigit(char) {
			alias.WriteRune(char)
		} else {
			alias.WriteByte('_')
		}
	}
	return alias.String()
}

func nearestModule(dir string) (string, string, error) {
	current := dir
	for {
		goModPath := filepath.Join(current, "go.mod")
		content, err := os.ReadFile(goModPath)
		if err == nil {
			for _, line := range strings.Split(string(content), "\n") {
				fields := strings.Fields(line)
				if len(fields) >= 2 && fields[0] == "module" &&
					(len(fields) == 2 || strings.HasPrefix(fields[2], "//")) {
					return current, fields[1], nil
				}
			}
			return "", "", fmt.Errorf("%s has no module directive", goModPath)
		}
		if !os.IsNotExist(err) {
			return "", "", err
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", "", fmt.Errorf("no go.mod found above %s", dir)
		}
		current = parent
	}
}

func requireFunction(dir, name string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read compiler plugin implementation directory: %w", err)
	}
	fset := token.NewFileSet()
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, entry.Name()), nil, 0)
		if err != nil {
			return err
		}
		for _, declaration := range file.Decls {
			function, ok := declaration.(*goast.FuncDecl)
			if ok && function.Recv == nil && function.Name.Name == name {
				return nil
			}
		}
	}
	return fmt.Errorf("compiler plugin function %s not found in %s", name, dir)
}
