// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

# Possible return types of the data provider function.
public type DataProviderReturnType error|map<AnyOrError[]>|AnyOrError[][];

type AnyOrError any|error;

# Represents errors generated by the Testerina module.
public type TestError distinct error;

// jballerina attaches `functionName` as this error's typed detail record and
// reads it back via `.detail().functionName` (execute.bal's
// printExecutionError). `error:detail()` isn't implemented in this
// interpreter (confirmed with a standalone repro) — see TODO.md — so
// ExecutionError instead threads functionName as a message prefix (see
// execute.bal's executeFunction/printExecutionError).
type ExecutionError distinct error;

type ModuleRerunJson record {|
    string[] testNames;
    map<string?> testModuleNames;
    map<string[]> subTestNames;
|};

// No jballerina equivalent: jballerina builds an ad hoc `map<json>` per test
// entry for moduleStatusReport's `map<json> output`. This port has no generic
// `json` support to build/serialize that with (see TODO.md), so
// writeModuleStatusReport takes an explicit, typed array of these instead.
type TestStatusEntry record {|
    string name;
    string status;
    string? failureMessage = ();
|};

enum TestType {
    GENERAL_TEST,
    DATA_DRIVEN_TUPLE_OF_TUPLE,
    DATA_DRIVEN_MAP_OF_TUPLE
}

enum TestCompletionStatus {
    YET_TO_COMPLETE,
    SUSPENDED,
    COMPLETED
}
